account/urls.py
from django.urls import path

from .views import (
    UsersList, CreateUser, UpdateUser, DeleteUser, SearchUsers,
    GroupList, CreateGroup, UpdateGroup, DeleteGroup, SearchGroups,
    EditAccount, ChangeUserPassword
)

app_name = "account"

urlpatterns = [
    path('users/', UsersList.as_view(), name="users"),
    path('users/page/<int:page>', UsersList.as_view(), name="users"),
    path('users/search', SearchUsers.as_view(), name="users_search"),
    path('users/search/page/<int:page>', SearchUsers.as_view(), name="users_search"),
    path('users/create', CreateUser.as_view(), name="user_create"),
    path('users/update/<int:pk>', UpdateUser.as_view(), name="user_update"),
    path('users/change_password/<int:pk>', ChangeUserPassword.as_view(), name="change_user_password"),
    path('users/delete/<int:pk>', DeleteUser.as_view(), name="user_delete"),

    path('groups/', GroupList.as_view(), name="groups"),
    path('groups/page/<int:page>', GroupList.as_view(), name="groups"),
    path('groups/search', SearchGroups.as_view(), name="groups_search"),
    path('groups/search/page/<int:page>', SearchGroups.as_view(), name="groups_search"),
    path('groups/create', CreateGroup.as_view(), name="group_create"),
    path('groups/update/<int:pk>', UpdateGroup.as_view(), name="group_update"),
    path('groups/delete/<int:pk>', DeleteGroup.as_view(), name="group_delete"),

    path('edit_account/<str:username>', EditAccount.as_view(), name="edit_account")
] 

configs/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from .views import index
from account.views import Login, log_out, ChangePassword

urlpatterns = [
    path('', index, name="index"),
    path('government_accounts/', include('government_accounts.urls')),
    path('non_government_accounts/', include('non_government_accounts.urls')),
    path('projects/', include('projects.urls')),
    path('cheques_receive_pay/', include('cheques_receive_pay.urls')),
    path('warehousing/', include('warehousing.urls')),
    path('projects_docs/', include('projects_docs.urls')),
    path('login/', Login.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('change_password/', ChangePassword.as_view(), name='change_password'),
    path('account/', include('account.urls')),
    path('reports/', include('reports.urls')),
    path('user_messages/', include('user_messages.urls')),
    path('admin/', admin.site.urls, name="home"),
]

handler404 = 'configs.views.custom_404'
handler500 = 'configs.views.custom_500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path

from .views import (
    OwnersList, OwnerCreate, OwnerUpdate, OwnerDelete, OwnerSearch,
    ProjectList, ProjectCreate, ProjectUpdate, ProjectDelete, ProjectSearch,
    WorkReferenceList, WorkReferenceCreate, WorkReferenceUpdate, WorkReferenceDelete, WorkReferenceSearch,
    CostsList, CostsCreate, CostsUpdate, CostsDelete, CostsSearch,
    PaymentsImagesList, PaymentsImagesCreate, PaymentsImagesUpdate, PaymentsImagesDelete, PaymentsImagesSearch
)




app_name = "projects"

urlpatterns = [
    path('owners/', OwnersList.as_view(), name='owners'),
    path('owners/page/<int:page>', OwnersList.as_view(), name='owners'),
    path('owners/search', OwnerSearch.as_view(), name='owners_search'),
    path('owners/search/page/<int:page>', OwnerSearch.as_view(), name='owners_search'),
    path('owners/create', OwnerCreate.as_view(), name='owner_create'),
    path('owners/update/<int:pk>', OwnerUpdate.as_view(), name='owner_update'),
    path('owners/delete/<int:pk>', OwnerDelete.as_view(), name='owner_delete'),

    path('projects/', ProjectList.as_view(), name='projects'),
    path('projects/page/<int:page>', ProjectList.as_view(), name='projects'),
    path('projects/search', ProjectSearch.as_view(), name='projects_search'),
    path('projects/search/page/<int:page>', ProjectSearch.as_view(), name='projects_search'),
    path('projects/create', ProjectCreate.as_view(), name='project_create'),
    path('projects/update/<int:pk>', ProjectUpdate.as_view(), name='project_update'),
    path('projects/delete/<int:pk>', ProjectDelete.as_view(), name='project_delete'),

    path('work_references/', WorkReferenceList.as_view(), name='work_references'),
    path('work_references/page/<int:page>', WorkReferenceList.as_view(), name='work_references'),
    path('work_references/search', WorkReferenceSearch.as_view(), name='work_references_search'),
    path('work_references/search/page/<int:page>', WorkReferenceSearch.as_view(), name='work_references_search'),
    path('work_references/create', WorkReferenceCreate.as_view(), name='work_reference_create'),
    path('work_references/update/<int:pk>', WorkReferenceUpdate.as_view(), name='work_reference_update'),
    path('work_references/delete/<int:pk>', WorkReferenceDelete.as_view(), name='work_reference_delete'),

    path('costs/', CostsList.as_view(), name='costs'),
    path('costs/page/<int:page>', CostsList.as_view(), name='costs'),
    path('costs/search', CostsSearch.as_view(), name='costs_search'),
    path('costs/search/page/<int:page>', CostsSearch.as_view(), name='costs_search'),
    path('costs/create', CostsCreate.as_view(), name='cost_create'),
    path('costs/update/<int:pk>', CostsUpdate.as_view(), name='cost_update'),
    path('costs/delete/<int:pk>', CostsDelete.as_view(), name='cost_delete'),

    path('payments_images/', PaymentsImagesList.as_view(), name='payments_images'),
    path('payments_images/page/<int:page>', PaymentsImagesList.as_view(), name='payments_images'),
    path('payments_images/search', PaymentsImagesSearch.as_view(), name='payments_images_search'),
    path('payments_images/search/page/<int:page>', PaymentsImagesSearch.as_view(), name='payments_images_search'),
    path('payments_images/create', PaymentsImagesCreate.as_view(), name='payments_image_create'),
    path('payments_images/update/<int:pk>', PaymentsImagesUpdate.as_view(), name='payments_image_update'),
    path('payments_images/delete/<int:pk>', PaymentsImagesDelete.as_view(), name='payments_image_delete'),
]

projects/models.py
from django.db import models
from django.db.models.query import Q

from django_jalali.db import models as jmodels



class OwnersManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(full_name__icontains=query) 
        )
        return self.get_queryset().filter(lookup).distinct()


class Owners(models.Model):
    full_name = models.CharField(max_length=250, verbose_name="نام و نام خانوادگی")
    phone = models.CharField(max_length=20, verbose_name="شماره تماس")
    national_card_image = models.ImageField(upload_to='images/owners/national_cards', null=True, blank=True, verbose_name="تصویر کارت ملی")
    birth_certificate_image = models.ImageField(upload_to='images/owners/birth_certificates', null=True, blank=True, verbose_name="تصویر شناسنامه")
    ownership_document_image = models.ImageField(upload_to='images/owners/ownership_documents', null=True, blank=True, verbose_name="تصویر سند مالکیت")

    objects = OwnersManager()

    class Meta:
        verbose_name = "مالک"
        verbose_name_plural = "مالکین"


    def __str__(self):
        return self.full_name


class ProjectManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(title__icontains=query) |
            Q(owners__full_name__icontains=query) 
        )
        return self.get_queryset().filter(lookup).distinct()


class Project(models.Model):
    CONTRACT_CHOICES = (
        ('pc', 'مشارکت در ساخت'),
        ('ow', 'مالکیت'),
        ('pa', 'شراکتی'),
        ('co', 'پیمانی'),
    )
    title = models.CharField(max_length=250, verbose_name="عنوان پروژه")
    contract_type = models.CharField(max_length=2, choices=CONTRACT_CHOICES, verbose_name="نوع قرارداد")
    owners = models.ManyToManyField(Owners, related_name="projects", verbose_name="مالکین")
    contractual_salary = models.PositiveBigIntegerField(default=0, blank=True, null=True, verbose_name="دستمزد قرارداد پیمانی")
    contractual_percentage = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=00.00, verbose_name="درصد قرارداد پیمانی") # type: ignore

    objects = ProjectManager()

    class Meta:
        verbose_name = "پروژه"
        verbose_name_plural = "پروژه‌ها"

    def __str__(self):
        return self.title
    
    def owners_to_str(self):
        return " ،".join([owners.full_name for owners in self.owners.all()])
    owners_to_str.short_description = "مالکین"

    def formatted_contractual_salary(self):
        return "{:,}".format(self.contractual_salary)
    
    def persian_contract_type(self):
        if self.contract_type == 'pc':
            return 'مشارکت در ساخت'
        elif self.contract_type == 'ow':
            return 'مالکیت'
        elif self.contract_type == 'pa':
            return 'شراکتی'
        else:
            return 'پیمانی'


class WorkReferenceManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(project__title__icontains=query) |
            Q(activity_type__icontains=query) |
            Q(referrer__icontains=query) |
            Q(doing_agent__icontains=query) 
        )
        return self.get_queryset().filter(lookup).distinct()


class WorkReference(models.Model):
    project = models.ForeignKey(Project, 
                                on_delete=models.CASCADE, 
                                related_name='project_work_references',
                                verbose_name='پروژه'
                            )
    activity_type = models.CharField(max_length=250, verbose_name='نوع فعالیت')
    referrer = models.CharField(max_length=250, verbose_name='ارجاع دهنده')
    doing_agent = models.CharField(max_length=250, verbose_name='مأمور انجام')
    follow_confirm = models.BooleanField(default=False, verbose_name='تأیید پیگیری')
    result_explan = models.TextField(verbose_name='توضیح نتیجه')
    follow_date = jmodels.jDateField(verbose_name='تاریخ پیگیری')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = WorkReferenceManager()

    class Meta:
        verbose_name = "ارجاع کار"
        verbose_name_plural = "ارجاع کارها"

    def __str__(self):
        return self.activity_type
    

class CostsManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(project__title__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()
    

class Costs(models.Model):
    project = models.ForeignKey(Project, 
                                on_delete=models.CASCADE, 
                                related_name='project_costs',
                                verbose_name='پروژه'
                            )
    # branches costs
    water_branch = models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب آب')
    electricity_branch = models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب برق')
    gas_branch = models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب گاز')
    phone_subscription = models.PositiveIntegerField(default=0, verbose_name='هزینه اشتراک تلفن')
    # engineer costs
    designer_office = models.PositiveIntegerField(default=0, verbose_name='هزینه دفتر طراح')
    supervisors = models.PositiveIntegerField(default=0, verbose_name='هزینه ناظرین')
    engineer_system = models.PositiveIntegerField(default=0, verbose_name='هزینه نظام مهندسی')
    sketch_map = models.PositiveIntegerField(default=0, verbose_name='هزینه تهیه نقشه کروکی')
    # mayoralty costs
    export_permit = models.PositiveIntegerField(default=0, verbose_name='هزینه صدور پروانه')
    export_end_work = models.PositiveIntegerField(default=0, verbose_name='هزینه صدور پایان کار')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = CostsManager()


    class Meta:
        verbose_name = "هزینه"
        verbose_name_plural = "هزینه ها"

    def __str__(self):
        return self.project.title
    
    def formatted_water_branch(self):
        return "{:,}".format(self.water_branch)
    
    def formatted_electricity_branch(self):
        return "{:,}".format(self.electricity_branch)
    
    def formatted_gas_branch(self):
        return "{:,}".format(self.gas_branch)
    
    def formatted_phone_subscription(self):
        return "{:,}".format(self.phone_subscription)
    
    def formatted_designer_office(self):
        return "{:,}".format(self.designer_office)
    
    def formatted_supervisors(self):
        return "{:,}".format(self.supervisors)
    
    def formatted_engineer_system(self):
        return "{:,}".format(self.engineer_system)
    
    def formatted_sketch_map(self):
        return "{:,}".format(self.sketch_map)
    
    def formatted_export_permit(self):
        return "{:,}".format(self.export_permit)
    
    def formatted_export_end_work(self):
        return "{:,}".format(self.export_end_work)
    

class PaymentsImagesManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(project__title__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class PaymentsImages(models.Model):
    project = models.ForeignKey(Project, 
                                on_delete=models.CASCADE, 
                                related_name='project_payment_receipts',
                                verbose_name='پروژه'
                            )
    
    designer_office = models.ImageField(upload_to='images/payment_receipts/designer_office', null=True, blank=True, verbose_name='دفتر طراح')
    supervisors = models.ImageField(upload_to='images/payment_receipts/supervisors', null=True, blank=True, verbose_name='ناظرین')
    engineer_system = models.ImageField(upload_to='images/payment_receipts/engineer_system', null=True, blank=True, verbose_name='نظام مهندسی')
    sketch_map = models.ImageField(upload_to='images/payment_receipts/sketch_map', null=True, blank=True, verbose_name='نقشه کروکی')
    export_permit = models.ImageField(upload_to='images/payment_receipts/export_permit', null=True, blank=True, verbose_name='عوارض صدور پروانه')
    visit_toll = models.ImageField(upload_to='images/payment_receipts/visit_toll', null=True, blank=True, verbose_name='عوارض بازدید')
    education_share = models.ImageField(upload_to='images/payment_receipts/education_share', null=True, blank=True, verbose_name='سهم آموزش و پرورش')
    fire_stations_share = models.ImageField(upload_to='images/payment_receipts/fire_stations_share', null=True, blank=True, verbose_name='سهم آتشنشانی')
    social_security_share = models.ImageField(upload_to='images/payment_receipts/social_security_share', null=True, blank=True, verbose_name='سهم تأمین اجتماعی')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = PaymentsImagesManager()
    

    class Meta:
        verbose_name = "تصویر فیش پرداختی"
        verbose_name_plural = "تصاویر فیش های پرداختی"


    def __str__(self):
        return self.project.title
    

templates/projects/cost_create_update.html
{% extends 'base_create_update.html' %}
{% load static %}

{% block title %}
    {% if request.resolver_match.url_name == 'cost_create' %}
        ثبت هزینه‌ها
    {% else %}
        ویرایش هزینه‌ها
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'cost_create' %}
        <span>ثبت هزینه‌ها</span>
    {% else %}
        <span>ویرایش هزینه‌ها</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "projects/forms/cost_form.html" %}
{% endblock %}

{% block form_control %}
    <script src="{% static 'scripts/projects/cost_form.js' %}"></script>
{% endblock %}

templates/projects/costs_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست هزینه‌ها{% endblock %}

{% block page_title %}لیست هزینه‌ها{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='ثبت هزینه‌' create_perm=perms.projects.add_costs %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include "projects/tables/costs_table.html" %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/projects/costs_list.js' %}"></script>
{% endblock %}

templates/projects/owner_create_update.html
{% extends 'base_create_update.html' %}

{% block title %}
    {% if request.resolver_match.url_name == 'owner_create' %}
        افزودن مالک
    {% else %}
        ویرایش مالک
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'owner_create' %}
        <span>افزودن مالک</span>
    {% else %}
        <span>ویرایش مالک</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "projects/forms/owner_form.html" %}
{% endblock %}

templates/projects/owner_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست مالکین{% endblock %}

{% block page_title %}لیست مالکین{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='افزودن مالک' create_perm=perms.projects.add_owners %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include "projects/tables/owners_table.html" %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}
    
{% block filter_control %}
    <script src="{% static 'scripts/projects/owners_list.js' %}"></script>
{% endblock %}

templates/projects/payments_image_create_update.html
{% extends 'base_create_update.html' %}

{% block title %}
    {% if request.resolver_match.url_name == 'payments_image_create' %}
        ثبت تصاویر فیش‌های پرداختی
    {% else %}
        ویرایش تصاویر فیش‌های پرداختی
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'payments_image_create' %}
        <span>ثبت تصاویر فیش‌های پرداختی</span>
    {% else %}
        <span>ویرایش تصاویر فیش‌های پرداختی</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "projects/forms/payments_image_form.html" %}
{% endblock %}

templates/projects/payments_image_pagination.html
{% extends "partials/base_pagination.html" %}

{% block previous_page_url %}
    {% if 'search' in request.resolver_match.url_name %}
        {% url "projects:payments_images_search" page_obj.previous_page_number %}?data_search={{ query }}
    {% else %}
        {% url "projects:payments_images" page_obj.previous_page_number %}
    {% endif %}
{% endblock  %}

{% block page_item_url %}
    {% if 'search' in request.resolver_match.url_name %}
        {% url "projects:payments_images_search" page_item %}?data_search={{ query }}
    {% else %}
        {% url "projects:payments_images" page_item %}
    {% endif %}
{% endblock  %}

{% block next_page_url %}
    {% if 'search' in request.resolver_match.url_name %}
        {% url "projects:payments_images_search" page_obj.next_page_number %}?data_search={{ query }}
    {% else %}
        {% url "projects:payments_images" page_obj.next_page_number %}
    {% endif %}
{% endblock  %}

templates/projects/payments_images_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست تصاویر فیش‌های پرداختی{% endblock %}

{% block page_title %}لیست تصاویر فیش‌های پرداختی{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='ثبت تصاویر فیش‌های پرداختی' create_perm=perms.projects.add_paymentsimages %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include 'projects/tables/payments_image_table.html' %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/projects/payments_images_list.js' %}"></script>
{% endblock %}

templates/projects/project_create_update.html
{% extends 'base_create_update.html' %}
{% load static %}

{% block title %}
    {% if request.resolver_match.url_name == 'project_create' %}
        افزودن پروژه
    {% else %}
        ویرایش پروژه
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'project_create' %}
        <span>افزودن پروژه</span>
    {% else %}
        <span>ویرایش پروژه</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "projects/forms/project_form.html" %}
{% endblock %}

{% block form_control %}
    <script src="{% static 'scripts/projects/project_form.js' %}"></script>
{% endblock %}

templates/projects/project_filter.html
{% extends "partials/search_print.html" %}

{% block filter %}
    <div class="form-group col-11 col-xl-3">
        <select name="contract_type" class="form-control" id="contract-type">
            <option value="all" selected>فیلتر نوع قرارداد</option>
            <option value="pc" {% if request.GET.contract_type == 'pc' %}selected{% endif %}>مشارکت در ساخت</option>
            <option value="ow" {% if request.GET.contract_type == 'ow' %}selected{% endif %}>مالکیت</option>
            <option value="pa" {% if request.GET.contract_type == 'pa' %}selected{% endif %}>شراکتی</option>
            <option value="co" {% if request.GET.contract_type == 'co' %}selected{% endif %}>پیمانی</option>
        </select>
    </div>
{% endblock %}

templates/projects/project_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست پروژه‌ها{% endblock %}

{% block page_title %}لیست پروژه‌ها{% endblock %}

{% block filter %}
    {% include 'projects/filters/projects_filter.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='افزودن پروژه' create_perm=perms.projects.add_project %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include 'projects/tables/projects_table.html' %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}
    
{% block filter_control %}
    <script src="{% static 'scripts/projects/projects_list.js' %}"></script>
{% endblock %}

templates/projects/project_pagination.html
{% extends "partials/base_pagination.html" %}

{% block previous_page_url %}
    {% if 'search' in request.resolver_match.url_name %}
        {% url "projects:projects_search" page_obj.previous_page_number %}?data_search={{ query }}&contract_type={{ contract_filter }}
    {% else %}
        {% url "projects:projects" page_obj.previous_page_number %}
    {% endif %}
{% endblock  %}

{% block page_item_url %}
    {% if 'search' in request.resolver_match.url_name %}
        {% url "projects:projects_search" page_item %}?data_search={{ query }}&contract_type={{ contract_filter }}
    {% else %}
        {% url "projects:projects" page_item %}
    {% endif %}
{% endblock  %}

{% block next_page_url %}
    {% if 'search' in request.resolver_match.url_name %}
        {% url "projects:projects_search" page_obj.next_page_number %}?data_search={{ query }}&contract_type={{ contract_filter }}
    {% else %}
        {% url "projects:projects" page_obj.next_page_number %}
    {% endif %}
{% endblock  %}

templates/projects/work_reference_create_update.html
{% extends 'base_create_update.html' %}
{% load static %}

{% block title %}
    {% if request.resolver_match.url_name == 'work_reference_create' %}
        ثبت ارجاع کار
    {% else %}
        ویرایش ارجاع کار
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'work_reference_create' %}
        <span>ثبت ارجاع کار</span>
    {% else %}
        <span>ویرایش ارجاع کار</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "projects/forms/work_reference_form.html" %}
{% endblock %}

{% block form_control %}
    <script src="{% static 'scripts/projects/work_reference_form.js' %}"></script>
{% endblock %}

templates/projects/work_references_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست ارجاع کارها{% endblock %}

{% block page_title %}لیست ارجاع کارها{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=True list_url=list_url create_url=create_url title='ثبت ارجاع کار' create_perm=perms.projects.add_workreference %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include 'projects/tables/work_reference_table.html' %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}
    
{% block filter_control %}
    <script src="{% static 'scripts/projects/work_reference_list.js' %}"></script>
{% endblock %}