account/urls.py
from django.urls import path

from .views import (
    UsersList, CreateUser, UpdateUser, DeleteUser, SearchUsers,
    GroupList, CreateGroup, UpdateGroup, DeleteGroup, SearchGroups,
    EditAccount, ChangeUserPassword
)

app_name = "account"

urlpatterns = [
    path('users/', UsersList.as_view(), name="users"),
    path('users/page/<int:page>', UsersList.as_view(), name="users"),
    path('users/search', SearchUsers.as_view(), name="users_search"),
    path('users/search/page/<int:page>', SearchUsers.as_view(), name="users_search"),
    path('users/create', CreateUser.as_view(), name="user_create"),
    path('users/update/<int:pk>', UpdateUser.as_view(), name="user_update"),
    path('users/change_password/<int:pk>', ChangeUserPassword.as_view(), name="change_user_password"),
    path('users/delete/<int:pk>', DeleteUser.as_view(), name="user_delete"),

    path('groups/', GroupList.as_view(), name="groups"),
    path('groups/page/<int:page>', GroupList.as_view(), name="groups"),
    path('groups/search', SearchGroups.as_view(), name="groups_search"),
    path('groups/search/page/<int:page>', SearchGroups.as_view(), name="groups_search"),
    path('groups/create', CreateGroup.as_view(), name="group_create"),
    path('groups/update/<int:pk>', UpdateGroup.as_view(), name="group_update"),
    path('groups/delete/<int:pk>', DeleteGroup.as_view(), name="group_delete"),

    path('edit_account/<str:username>', EditAccount.as_view(), name="edit_account")
] 

configs/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from .views import index
from account.views import Login, log_out, ChangePassword

urlpatterns = [
    path('', index, name="index"),
    path('government_accounts/', include('government_accounts.urls')),
    path('non_government_accounts/', include('non_government_accounts.urls')),
    path('projects/', include('projects.urls')),
    path('cheques_receive_pay/', include('cheques_receive_pay.urls')),
    path('warehousing/', include('warehousing.urls')),
    path('projects_docs/', include('projects_docs.urls')),
    path('login/', Login.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('change_password/', ChangePassword.as_view(), name='change_password'),
    path('account/', include('account.urls')),
    path('reports/', include('reports.urls')),
    path('user_messages/', include('user_messages.urls')),
    path('admin/', admin.site.urls, name="home"),
]

handler404 = 'configs.views.custom_404'
handler500 = 'configs.views.custom_500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

non_government_accounts/urls.py
from django.urls import path

from .views import (
    ContractorsList, ContractorCreate, ContractorUpdate, ContractorDelete, ContractorSearch,
    SuppliersList, SupplierCreate, SupplierUpdate, SupplierDelete, SupplierSearch,
    PersonnelList, PersonnelCreate, PersonnelUpdate, PersonnelDelete, PersonnelSearch,
    PartnersList, PartnersCreate, PartnersUpdate, PartnersDelete, PartnerSearch,
    BuyersSellersList, BuyersSellersCreate, BuyersSellersUpdate, BuyersSellersDelete, BuyersSellersSearch,
    OrdersList, OrdersCreate, OrdersUpdate, OrdersDelete, OrdersSearch,
    ConflictOrdersList, ConflictOrdersCreate, ConflictOrdersUpdate, ConflictOrdersDelete, ConflictOrdersSearch
)


app_name = "non_government_accounts"

urlpatterns = [
    path('contractors/', ContractorsList.as_view(), name='contractors'),
    path('contractors/page/<int:page>', ContractorsList.as_view(), name="contractors"),
    path('contractors/search', ContractorSearch.as_view(), name='contractors_search'),
    path('contractors/search/page/<int:page>', ContractorSearch.as_view(), name="contractors_search"),
    path('contractors/create', ContractorCreate.as_view(), name='contractor_create'),
    path('contractors/update/<int:pk>', ContractorUpdate.as_view(), name='contractor_update'),
    path('contractors/delete/<int:pk>', ContractorDelete.as_view(), name='contractor_delete'),

    path('suppliers/', SuppliersList.as_view(), name='suppliers'),
    path('suppliers/page/<int:page>', SuppliersList.as_view(), name='suppliers'),
    path('suppliers/search', SupplierSearch.as_view(), name='suppliers_search'),
    path('suppliers/search/page/<int:page>', SupplierSearch.as_view(), name='suppliers_search'),
    path('suppliers/create', SupplierCreate.as_view(), name='supplier_create'),
    path('suppliers/update/<int:pk>', SupplierUpdate.as_view(), name='supplier_update'),
    path('suppliers/delete/<int:pk>', SupplierDelete.as_view(), name='supplier_delete'),

    path('personnel/', PersonnelList.as_view(), name='personnel'),
    path('personnel/page/<int:page>', PersonnelList.as_view(), name='personnel'),
    path('personnel/search', PersonnelSearch.as_view(), name='personnel_search'),
    path('personnel/search/page/<int:page>', PersonnelSearch.as_view(), name='personnel_search'),
    path('personnel/create', PersonnelCreate.as_view(), name='personnel_create'),
    path('personnel/update/<int:pk>', PersonnelUpdate.as_view(), name='personnel_update'),
    path('personnel/delete/<int:pk>', PersonnelDelete.as_view(), name='personnel_delete'),

    path('partners/', PartnersList.as_view(), name='partners'),
    path('partners/page/<int:page>', PartnersList.as_view(), name='partners'),
    path('partners/search', PartnerSearch.as_view(), name='partners_search'),
    path('partners/search/page/<int:page>', PartnerSearch.as_view(), name='partners_search'),
    path('partners/create', PartnersCreate.as_view(), name='partner_create'),
    path('partners/update/<int:pk>', PartnersUpdate.as_view(), name='partner_update'),
    path('partners/delete/<int:pk>', PartnersDelete.as_view(), name='partner_delete'),

    path('buyers_sellers/', BuyersSellersList.as_view(), name='buyers_sellers'),
    path('buyers_sellers/page/<int:page>', BuyersSellersList.as_view(), name='buyers_sellers'),
    path('buyers_sellers/search', BuyersSellersSearch.as_view(), name='buyers_sellers_search'),
    path('buyers_sellers/search/page/<int:page>', BuyersSellersSearch.as_view(), name='buyers_sellers_search'),
    path('buyers_sellers/create', BuyersSellersCreate.as_view(), name='buyer_seller_create'),
    path('buyers_sellers/update/<int:pk>', BuyersSellersUpdate.as_view(), name='buyer_seller_update'),
    path('buyers_sellers/delete/<int:pk>', BuyersSellersDelete.as_view(), name='buyer_seller_delete'),

    path('orders/', OrdersList.as_view(), name='orders'),
    path('orders/page/<int:page>', OrdersList.as_view(), name='orders'),
    path('orders/search', OrdersSearch.as_view(), name='orders_search'),
    path('orders/search/page/<int:page>', OrdersSearch.as_view(), name='orders_search'),
    path('orders/create', OrdersCreate.as_view(), name='order_create'),
    path('orders/update/<int:pk>', OrdersUpdate.as_view(), name='order_update'),
    path('orders/delete/<int:pk>', OrdersDelete.as_view(), name='order_delete'),

    path('conflict_orders/', ConflictOrdersList.as_view(), name='conflict_orders'),
    path('conflict_orders/page/<int:page>', ConflictOrdersList.as_view(), name='conflict_orders'),
    path('conflict_orders/search', ConflictOrdersSearch.as_view(), name='conflict_orders_search'),
    path('conflict_orders/search/page/<int:page>', ConflictOrdersSearch.as_view(), name='conflict_orders_search'),
    path('conflict_orders/create', ConflictOrdersCreate.as_view(), name='conflict_order_create'),
    path('conflict_orders/update/<int:pk>', ConflictOrdersUpdate.as_view(), name='conflict_order_update'),
    path('conflict_orders/delete/<int:pk>', ConflictOrdersDelete.as_view(), name='conflict_order_delete'),
]

non_government_accounts/models.py
from django.db import models
from django.db.models.query import Q

from django_jalali.db import models as jmodels

from projects.models import Project



class ContractorsManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(full_name__icontains=query) |
            Q(job__icontains=query) |
            Q(project__title__icontains=query) |
            Q(address__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class Contractors(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_contractors', verbose_name="پروژه")
    full_name = models.CharField(max_length=250, verbose_name="نام و نام خانوادگی")
    job = models.CharField(max_length=100, verbose_name="رشته شغلی")
    phone = models.CharField(max_length=20, verbose_name="شماره تماس")
    address = models.TextField(verbose_name="آدرس")

    objects = ContractorsManager()

    class Meta:
        verbose_name = "پیمانکار"
        verbose_name_plural = "پیمانکاران"


    def __str__(self):
        return self.full_name


class SuppliersManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(full_name__icontains=query) |
            Q(job__icontains=query) |
            Q(project__title__icontains=query) |
            Q(address__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class Suppliers(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_suppliers', verbose_name="پروژه")
    full_name = models.CharField(max_length=250, verbose_name="نام و نام خانوادگی")
    job = models.CharField(max_length=100, verbose_name="رشته شغلی")
    phone = models.CharField(max_length=20, verbose_name="شماره تماس")
    address = models.TextField(verbose_name="آدرس")

    objects = SuppliersManager()

    class Meta:
        verbose_name = "تأمین کننده"
        verbose_name_plural = "تأمین کنندگان"


    def __str__(self):
        return self.full_name


class PersonnelManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(full_name__icontains=query) |
            Q(job__icontains=query) |
            Q(address__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class Personnel(models.Model):
    full_name = models.CharField(max_length=250, verbose_name="نام و نام خانوادگی")
    job = models.CharField(max_length=100, verbose_name="رشته شغلی")
    phone = models.CharField(max_length=20, verbose_name="شماره تماس")
    address = models.TextField(verbose_name="آدرس")
    contract_image = models.ImageField(upload_to='images/personnel', null=True, blank=True, verbose_name="تصویر قرارداد")

    objects = PersonnelManager()

    class Meta:
        verbose_name = "پرسنل"
        verbose_name_plural = "پرسنل"


    def __str__(self):
        return self.full_name
    

class PartnersManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(full_name__icontains=query) |
            Q(project__title__icontains=query) |
            Q(address__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()
    

class Partners(models.Model):
    investment_amount = models.PositiveBigIntegerField(default=0, verbose_name='مبلغ سرمایه‌گذاری')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_partners', verbose_name='پروژه')
    contract_image = models.ImageField(upload_to='images/partners', null=True, blank=True, verbose_name="تصویر قرارداد")
    full_name = models.CharField(max_length=250, verbose_name="نام و نام خانوادگی")
    address = models.TextField(verbose_name="آدرس")
    phone = models.CharField(max_length=20, verbose_name="شماره تماس")

    objects = PartnersManager()

    class Meta:
        verbose_name = "شریک"
        verbose_name_plural = "شرکاء"


    def __str__(self):
        return self.full_name
    
    def formatted_investment_amount(self):
        return "{:,}".format(self.investment_amount)


class BuyersSellersManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(full_name__icontains=query)|
            Q(address__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class BuyersSellers(models.Model):
    BUYER_SELLER_CHOICES = (
        ('buy', 'خریدار'),
        ('sel', 'فروشنده')
    )
    PAYMENT_ORDER_CHOICES = (
        ('csh', 'نقدی'),
        ('chq', 'چک'),
        ('del', 'حین تحویل'),
        ('dtr', 'انتقال سند'),
        ('afh', 'بعد از سفت‌ کاری'),
        ('aif', 'بعد از اجرای تأسیسات'),
        ('atc', 'بعد از کاشی و سرامیک'),
        ('afc', 'بعد از سقف طبقه'),
        ('aff', 'بعد از فونداسیون'),
        ('oth', 'سایر'),
    )
    
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_buyers_sellers', verbose_name='پروژه') # type: ignore
    buyer_seller = models.CharField(max_length=3, choices=BUYER_SELLER_CHOICES, verbose_name='خریدار / فروشنده')
    full_name = models.CharField(max_length=250, verbose_name="نام و نام خانوادگی")
    phone = models.CharField(max_length=20, verbose_name="شماره تماس")
    address = models.TextField(verbose_name="آدرس")
    contract_image = models.ImageField(upload_to='images/buyers_sellers', null=True, blank=True, verbose_name="تصویر قرارداد")
    payment_order = models.CharField(max_length=3, choices=PAYMENT_ORDER_CHOICES, verbose_name='ترتیب پرداخت')
    current_roof = models.CharField(max_length=50, blank=True, null=True, verbose_name="سقف کنونی")
    payment_amount = models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پرداختی')
    payment_date = jmodels.jDateField(verbose_name='تاریخ پرداخت')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = BuyersSellersManager()
    

    class Meta:
        verbose_name = "خریدار / فروشنده"
        verbose_name_plural = "خریداران / فروشندگان"


    def __str__(self):
        return self.full_name
    
    def formatted_payment_amount(self):
        return "{:,}".format(self.payment_amount)
    
    def persian_payment_order(self):
        if self.payment_order == 'csh':
            return 'نقدی'              
        elif self.payment_order == 'chq':
            return 'چک'
        elif self.payment_order == 'del':
            return 'حین تحویل'
        elif self.payment_order == 'dtr':
            return 'انتقال سند'
        elif self.payment_order == 'afh':
            return 'بعد از سفت کاری'
        elif self.payment_order == 'aif':
            return 'بعد از اجرای تأسیسات'
        elif self.payment_order == 'atc':
            return 'بعد از کاشی و سرامیک'
        elif self.payment_order == 'afc':
            return 'بعد از سقف طبقه'
        elif self.payment_order == 'aff':
            return 'بعد از فونداسیون'
        else:
            return 'سایر'
    

class OrdersManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(supplier__full_name__icontains=query)|
            Q(order_type__icontains=query)|
            Q(project__title__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class Orders(models.Model):
    MEASUREMENT_UNIT_CHOICES = (
        ('sqm', 'مترمربع'),
        ('mel', 'مترطول'),
        ('kgm', 'کیلوگرم'),
        ('ton', 'تن'),
        ('num', 'عدد'),
    )
    ORDER_RESULT_CHOICES = (
        ('spd', 'ارسال در تاریخ مشخص'),
        ('snd', 'ارسال شده'),
        ('cld', 'لغو شده'),
    )
    SENDED_IMAGE_TYPE_CHOICES = (
        ('blg', 'بارنامه'),
        ('fac', 'فاکتور'),
        ('enf', 'برگه ورود'),
        ('exf', 'برگه خروج'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_orders', verbose_name='پروژه')
    supplier = models.ForeignKey(Suppliers, on_delete=models.CASCADE, related_name='order_suppliers', verbose_name='تأمین کننده')
    order_type = models.CharField(max_length=100, verbose_name='نوع سفارش')
    measurement_unit = models.CharField(max_length=3, choices=MEASUREMENT_UNIT_CHOICES, verbose_name='واحد اندازه گیری')
    unit_price = models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد')
    order_amount = models.PositiveIntegerField(default=0, verbose_name='مقدار سفارش')
    order_total_price = models.PositiveBigIntegerField(default=0, editable=False)
    order_respite = models.PositiveSmallIntegerField(default=0, verbose_name='مهلت سفارش')
    order_result = models.CharField(max_length=3, choices=ORDER_RESULT_CHOICES, verbose_name='نتیجه سفارش')
    sended_image = models.ImageField(upload_to='images/sended_images', null=True, blank=True, verbose_name='تصویر سفارش ارسال شده')
    sended_image_type = models.CharField(max_length=3, choices=SENDED_IMAGE_TYPE_CHOICES, null=True, blank=True, verbose_name='نوع تصویر سفارش ارسال شده')
    explan_order_cancel = models.TextField(null=True, blank=True, verbose_name='توضیح علت لغو سفارش')
    order_date = jmodels.jDateField(verbose_name='تاریخ سفارش')
    sending_date = jmodels.jDateField(null=True, blank=True, verbose_name='تاریخ ارسال')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = OrdersManager()

    class Meta:
        verbose_name = "سفارش"
        verbose_name_plural = "سفارشات"


    def __str__(self):
        return f"{self.order_type} - {self.supplier} - پروژه {self.project.title}" # type: ignore

    def get_order_total_price(self):
        self.order_total_price = self.order_amount * self.unit_price
        return self.order_total_price
    get_order_total_price.short_description = 'قیمت کل سفارش'

    def formatted_unit_price(self): # type: ignore
        return "{:,}".format(self.unit_price)
    
    def formatted_order_amount(self):

templates/non_government_accounts/buyer_seller_create_update.html
{% extends 'base_create_update.html' %}
{% load static %}

{% block title %}
    {% if request.resolver_match.url_name == 'buyer_seller_create' %}
        افزودن خریدار / فروشنده
    {% else %}
        ویرایش خریدار / فروشنده
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'buyer_seller_create' %}
        <span>افزودن خریدار / فروشنده</span>
    {% else %}
        <span>ویرایش خریدار / فروشنده</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "non_government_accounts/forms/buyer_seller_form.html" %}
{% endblock %}

{% block form_control %}
    <script src="{% static 'scripts/non_government_accounts/buyer_seller_form.js' %}"></script>
{% endblock %}

templates/non_government_accounts/buyers_sellers_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست خریداران / فروشندگان{% endblock %}

{% block page_title %}لیست خریداران / فروشندگان{% endblock %}

{% block filter %}
    {% include 'non_government_accounts/filters/buyers_sellers_filter.html' with search_url=search_url date_filter=True list_url=list_url create_url=create_url title='افزودن خریدار / فروشنده' create_perm=perms.non_government_accounts.add_buyerssellers %} 
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include "non_government_accounts/tables/buyers_sellers_table.html" %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/non_government_accounts/buyers_sellers_list.js' %}"></script>
{% endblock %}

templates/non_government_accounts/conflict_order_create_update.html
{% extends 'base_create_update.html' %}

{% block title %}
    {% if request.resolver_match.url_name == 'conflict_order_create' %}
        ثبت مغایرت سفارش
    {% else %}
        ویرایش مغایرت سفارش
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'conflict_order_create' %}
        <span>ثبت مغایرت سفارش</span>
    {% else %}
        <span>ویرایش مغایرت سفارش</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "non_government_accounts/forms/conflict_order_form.html" %}
{% endblock %}

templates/non_government_accounts/conflict_orders_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست مغایرت سفارشات{% endblock %}

{% block page_title %}لیست مغایرت سفارشات{% endblock %}

{% block filter %}
    {% include 'non_government_accounts/filters/conflict_orders_filter.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='ثبت مغایرت سفارش' create_perm=perms.non_government_accounts.add_conflictorders %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include "non_government_accounts/tables/conflict_orders_table.html" %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/non_government_accounts/conflict_orders_list.js' %}"></script>
{% endblock %}

templates/non_government_accounts/contractors_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست پیمانکاران{% endblock %}

{% block page_title %}لیست پیمانکاران{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='افزودن پیمانکار' create_perm=perms.non_government_accounts.add_contractors %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include "non_government_accounts/tables/contractors_table.html" %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/non_government_accounts/contractors_list.js' %}"></script>
{% endblock %}

templates/non_government_accounts/orders_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست سفارشات{% endblock %}

{% block page_title %}لیست سفارشات{% endblock %}

{% block filter %}
    {% include 'non_government_accounts/filters/orders_filter.html' with search_url=search_url date_filter=True create_url=create_url list_url=list_url title='افزودن سفارش' create_perm=perms.non_government_accounts.add_orders %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include "non_government_accounts/tables/orders_table.html" %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/non_government_accounts/orders_list.js' %}"></script>
{% endblock %}

templates/non_government_accounts/partners_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست شرکاء{% endblock %}

{% block page_title %}لیست شرکاء{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='افزودن شریک' create_perm=perms.non_government_accounts.add_partners %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include "non_government_accounts/tables/partners_table.html" %}
{% endblock %}
    
{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}
    
{% block filter_control %}
    <script src="{% static 'scripts/non_government_accounts/partners_list.js' %}"></script>
{% endblock %}

templates/non_government_accounts/personnel_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست پرسنل{% endblock %}

{% block page_title %}لیست پرسنل{% endblock %}

{% block filter %}
{% include 'partials/search_print.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='افزودن پرسنل' create_perm=perms.non_government_accounts.add_personnel %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
{% include "non_government_accounts/tables/personnel_table.html" %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/non_government_accounts/personnel_list.js' %}"></script>
{% endblock %}

templates/non_government_accounts/suppliers_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست تأمین کنندگان{% endblock %}

{% block page_title %}لیست تأمین کنندگان{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=False list_url=list_url create_url=create_url title='افزودن تأمین کننده' create_perm=perms.non_government_accounts.add_suppliers %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}
    
{% block table %}
    {% include "non_government_accounts/tables/suppliers_table.html" %}
{% endblock %}
    
{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/non_government_accounts/suppliers_list.js' %}"></script>
{% endblock %}