account/urls.py
from django.urls import path

from .views import (
    UsersList, CreateUser, UpdateUser, DeleteUser, SearchUsers,
    GroupList, CreateGroup, UpdateGroup, DeleteGroup, SearchGroups,
    EditAccount, ChangeUserPassword
)

app_name = "account"

urlpatterns = [
    path('users/', UsersList.as_view(), name="users"),
    path('users/page/<int:page>', UsersList.as_view(), name="users"),
    path('users/search', SearchUsers.as_view(), name="users_search"),
    path('users/search/page/<int:page>', SearchUsers.as_view(), name="users_search"),
    path('users/create', CreateUser.as_view(), name="user_create"),
    path('users/update/<int:pk>', UpdateUser.as_view(), name="user_update"),
    path('users/change_password/<int:pk>', ChangeUserPassword.as_view(), name="change_user_password"),
    path('users/delete/<int:pk>', DeleteUser.as_view(), name="user_delete"),

    path('groups/', GroupList.as_view(), name="groups"),
    path('groups/page/<int:page>', GroupList.as_view(), name="groups"),
    path('groups/search', SearchGroups.as_view(), name="groups_search"),
    path('groups/search/page/<int:page>', SearchGroups.as_view(), name="groups_search"),
    path('groups/create', CreateGroup.as_view(), name="group_create"),
    path('groups/update/<int:pk>', UpdateGroup.as_view(), name="group_update"),
    path('groups/delete/<int:pk>', DeleteGroup.as_view(), name="group_delete"),

    path('edit_account/<str:username>', EditAccount.as_view(), name="edit_account")
] 

configs/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from .views import index
from account.views import Login, log_out, ChangePassword

urlpatterns = [
    path('', index, name="index"),
    path('government_accounts/', include('government_accounts.urls')),
    path('non_government_accounts/', include('non_government_accounts.urls')),
    path('projects/', include('projects.urls')),
    path('cheques_receive_pay/', include('cheques_receive_pay.urls')),
    path('warehousing/', include('warehousing.urls')),
    path('projects_docs/', include('projects_docs.urls')),
    path('login/', Login.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('change_password/', ChangePassword.as_view(), name='change_password'),
    path('account/', include('account.urls')),
    path('reports/', include('reports.urls')),
    path('user_messages/', include('user_messages.urls')),
    path('admin/', admin.site.urls, name="home"),
]

handler404 = 'configs.views.custom_404'
handler500 = 'configs.views.custom_500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

warehousing/urls.py
from django.urls import path

from .views import (
    StuffList, StuffCreate, StuffUpdate, StuffDelete, StuffSearch,
    WarehouseImportList, WarehouseImportCreate, WarehouseImportUpdate, WarehouseImportDelete, WarehouseImportSearch,
    WarehouseExportList, WarehouseExportCreate, WarehouseExportUpdate, WarehouseExportDelete, WarehouseExportSearch,
    UseCertificateList, UseCertificateCreate, UseCertificateUpdate, UseCertificateDelete, UseCertificateSearch,
    ProjectWarehouseList, ProjectWarehouseCreate, ProjectWarehouseUpdate, ProjectWarehouseDelete, ProjectWarehouseSearch
)



app_name = 'warehousing'

urlpatterns = [
    path('stuffs/', StuffList.as_view(), name='stuffs'),
    path('stuffs/page/<int:page>', StuffList.as_view(), name='stuffs'),
    path('stuffs/search', StuffSearch.as_view(), name='stuffs_search'),
    path('stuffs/search/page/<int:page>', StuffSearch.as_view(), name='stuffs_search'),
    path('stuffs/create', StuffCreate.as_view(), name='stuff_create'),
    path('stuffs/update/<int:pk>', StuffUpdate.as_view(), name='stuff_update'),
    path('stuffs/delete/<int:pk>', StuffDelete.as_view(), name='stuff_delete'),

    path('warehouse_imports/', WarehouseImportList.as_view(), name='warehouse_imports'),
    path('warehouse_imports/page/<int:page>', WarehouseImportList.as_view(), name='warehouse_imports'),
    path('warehouse_imports/search', WarehouseImportSearch.as_view(), name='warehouse_imports_search'),
    path('warehouse_imports/search/page/<int:page>', WarehouseImportSearch.as_view(), name='warehouse_imports_search'),
    path('warehouse_imports/create', WarehouseImportCreate.as_view(), name='warehouse_import_create'),
    path('warehouse_imports/update/<int:pk>', WarehouseImportUpdate.as_view(), name='warehouse_import_update'),
    path('warehouse_imports/delete/<int:pk>', WarehouseImportDelete.as_view(), name='warehouse_import_delete'),

    path('warehouse_exports/', WarehouseExportList.as_view(), name='warehouse_exports'),
    path('warehouse_exports/page/<int:page>', WarehouseExportList.as_view(), name='warehouse_exports'),
    path('warehouse_exports/search', WarehouseExportSearch.as_view(), name='warehouse_exports_search'),
    path('warehouse_exports/search/page/<int:page>', WarehouseExportSearch.as_view(), name='warehouse_exports_search'),
    path('warehouse_exports/create', WarehouseExportCreate.as_view(), name='warehouse_export_create'),
    path('warehouse_exports/update/<int:pk>', WarehouseExportUpdate.as_view(), name='warehouse_export_update'),
    path('warehouse_exports/delete/<int:pk>', WarehouseExportDelete.as_view(), name='warehouse_export_delete'),

    path('use_certificates/', UseCertificateList.as_view(), name='use_certificates'),
    path('use_certificates/page/<int:page>', UseCertificateList.as_view(), name='use_certificates'),
    path('use_certificates/search', UseCertificateSearch.as_view(), name='use_certificates_search'),
    path('use_certificates/search/page/<int:page>', UseCertificateSearch.as_view(), name='use_certificates_search'),
    path('use_certificates/create', UseCertificateCreate.as_view(), name='use_certificate_create'),
    path('use_certificates/update/<int:pk>', UseCertificateUpdate.as_view(), name='use_certificate_update'),
    path('use_certificates/delete/<int:pk>', UseCertificateDelete.as_view(), name='use_certificate_delete'),

    path('project_warehouses/', ProjectWarehouseList.as_view(), name='project_warehouses'),
    path('project_warehouses/page/<int:page>', ProjectWarehouseList.as_view(), name='project_warehouses'),
    path('project_warehouses/search', ProjectWarehouseSearch.as_view(), name='project_warehouses_search'),
    path('project_warehouses/search/page/<int:page>', ProjectWarehouseSearch.as_view(), name='project_warehouses_search'),
    path('project_warehouses/create', ProjectWarehouseCreate.as_view(), name='project_warehouse_create'),
    path('project_warehouses/update/<int:pk>', ProjectWarehouseUpdate.as_view(), name='project_warehouse_update'),
    path('project_warehouses/delete/<int:pk>', ProjectWarehouseDelete.as_view(), name='project_warehouse_delete'),
]

warehousing/models.py
from django.db import models
from django.db.models.query import Q

from django_jalali.db import models as jmodels

from projects.models import Project
from non_government_accounts.models import Suppliers, Personnel, Contractors




class StuffManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(stuff_type__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class Stuff(models.Model):
    MEASUREMENT_UNIT_CHOICES = (
        ('sqm', 'مترمربع'),
        ('mel', 'مترطول'),
        ('kgm', 'کیلوگرم'),
        ('ton', 'تن'),
        ('num', 'عدد'),
        ('bag', 'کیسه'),
    )
    stuff_type = models.CharField(max_length=100, verbose_name='نوع کالا')
    measurement_unit = models.CharField(max_length=3, choices=MEASUREMENT_UNIT_CHOICES, verbose_name='واحد اندازه گیری')
    
    objects = StuffManager()
    

    class Meta:
        verbose_name = "کالا"
        verbose_name_plural = "کالاها"

    def __str__(self):
        return f'{self.stuff_type} - واحد: {self.persian_measurement_unit()}'
    
    def persian_measurement_unit(self):
        if self.measurement_unit == "sqm":
            return 'مترمربع' 
        elif self.measurement_unit == "mel":
            return 'متر طول' 
        elif self.measurement_unit == "kgm":
            return 'کیلوگرم' 
        elif self.measurement_unit == "ton":
            return 'تن' 
        elif self.measurement_unit == "num":
            return 'عدد' 
        else:
            return 'کیسه'


class MainWarehouseImportManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(supplier__full_name__icontains=query)|
            Q(receiver__full_name__icontains=query)|
            Q(other_sender__icontains=query)|
            Q(stuff_type__stuff_type__icontains=query)|
            Q(project_returned__title__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class MainWarehouseImport(models.Model):
    # sender
    supplier = models.ForeignKey(Suppliers, on_delete=models.CASCADE, related_name='warehouse_import_suppliers', null=True, blank=True,verbose_name='تأمین کننده')
    other_sender = models.TextField(null=True, blank=True, verbose_name='سایر')
    # stuff
    stuff_type = models.ForeignKey(Stuff,on_delete=models.CASCADE,related_name='warehouse_import_stuffs',verbose_name='نوع کالا')
    stuff_amount = models.PositiveIntegerField(default=0, verbose_name='مقدار')
    receiver = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='warehouse_import_personnel', verbose_name='تحویل گیرنده')
    import_date = jmodels.jDateField(verbose_name='تاریخ ورود کالا')
    # returned
    is_returned = models.BooleanField(default=False, verbose_name='کالا مرجوعی است')
    project_returned = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='warehouse_returned_projects', null=True, blank=True,verbose_name='مرجوعی از پروژه')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = MainWarehouseImportManager()


    class Meta:
        verbose_name = "کالای افزوده شده به انبار"
        verbose_name_plural = "کالاهای افزوده شده به انبار"

    def __str__(self):
        return f"{self.stuff_type} - {self.date_time.year}/{self.date_time.month}/{self.date_time.day}" # type: ignore
    
    def formatted_stuff_amount(self):
        return "{:,}".format(self.stuff_amount)
    
    
class MainWarehouseExportManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(personnel__full_name__icontains=query)|
            Q(contractor__full_name__icontains=query)|
            Q(deliverer__full_name__icontains=query)|
            Q(stuff_type__stuff_type__icontains=query)|
            Q(project__title__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class MainWarehouseExport(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='warehouse_export_projects', verbose_name='پروژه')
    # applicant
    personnel = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='warehouse_export_personnel', null=True, blank=True, verbose_name='پرسنل')
    contractor = models.ForeignKey(Contractors, on_delete=models.CASCADE, related_name='warehouse_export_contractors', null=True, blank=True, verbose_name='پیمانکار')
    # stuff
    stuff_type = models.ForeignKey(Stuff, on_delete=models.CASCADE, related_name='warehouse_export_stuffs', verbose_name='نوع کالا')
    stuff_amount = models.PositiveIntegerField(default=0, verbose_name='مقدار')
    deliverer = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='warehouse_export_deliverers', verbose_name='تحویل دهنده')
    export_date = jmodels.jDateField(verbose_name='تاریخ خروج کالا')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = MainWarehouseExportManager()

    class Meta:
        verbose_name = "کالای خارج شده از انبار"
        verbose_name_plural = "کالاهای خارج شده از انبار"

    def __str__(self):
        return f"{self.stuff_type} - {self.project}"
    
    def formatted_stuff_amount(self):
        return "{:,}".format(self.stuff_amount)
    

class UseCertificateManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(project__title__icontains=query)|
            Q(stuff_type__stuff_type__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class UseCertificate(models.Model):
    RETURNED_TO_CHOICES = (
        ('prw', 'انبار پروژه'),
        ('maw', 'انبار اصلی'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='use_certificate_projects',verbose_name='پروژه')
    # stuff
    stuff_type = models.ForeignKey(Stuff, on_delete=models.CASCADE, related_name='use_certificate_stuffs', verbose_name='نوع کالا')
    is_deficient = models.BooleanField(default=False, verbose_name='کسری دارد')
    deficient_amount = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name='مقدار کسری')
    is_excess = models.BooleanField(default=False, verbose_name='مازاد دارد')
    excess_amount = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name='مقدار مازاد')
    start_using_date = jmodels.jDateField(verbose_name='تاریخ شروع مصرف')
    finish_using_date = jmodels.jDateField(verbose_name='تاریخ پایان مصرف')
    # returned
    returned_to = models.CharField(max_length=3, choices=RETURNED_TO_CHOICES, null=True, blank=True, verbose_name='مرجوعی به')
    return_date = jmodels.jDateField(null=True, blank=True, verbose_name='تاریخ ارجاع به انبار')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)
    
    objects = UseCertificateManager()

    class Meta:
        verbose_name = "گواهی مصرف کالا"
        verbose_name_plural = "گواهی‌های مصرف کالا"

    def __str__(self):
        return f"{self.project.title}-{self.stuff_type.stuff_type}: از {self.start_using_date.year}/{self.start_using_date.month}/{self.start_using_date.day} - تا {self.finish_using_date.year}/{self.finish_using_date.month}/{self.finish_using_date.day}"
    
    def formatted_deficient_amount(self):
        return "{:,}".format(self.deficient_amount)
    
    def formatted_excess_amount(self):
        return "{:,}".format(self.excess_amount)


class ProjectWarehouseManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(project__title__icontains=query)|
            Q(personnel_apply__full_name__icontains=query)|
            Q(contractor_apply__full_name__icontains=query)|
            Q(personnel_delivery__full_name__icontains=query)|
            Q(contractor_delivery__full_name__icontains=query)|
            Q(stuff_type__stuff_type__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class ProjectWarehouse(models.Model):
    STATUS_CHOICES = (
        ('exp', 'خروج از انبار'),
        ('imp', 'ورود به انبار'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_warehouse_projects',verbose_name='پروژه')
    # applicant
    personnel_apply = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='project_warehouse_personnel_applies',null=True, blank=True,verbose_name='پرسنل')
    contractor_apply = models.ForeignKey(Contractors, on_delete=models.CASCADE, related_name='project_warehouse_contractors_applies',null=True, blank=True,verbose_name='پیمانکار')
     # stuff
    stuff_type = models.ForeignKey(Stuff, on_delete=models.CASCADE, related_name='project_warehouse_stuffs', verbose_name='نوع کالا')
    stuff_amount = models.PositiveIntegerField(default=0, verbose_name='مقدار')
    # deliverer
    personnel_delivery = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='project_warehouse_personnel_deliveries',null=True, blank=True,verbose_name='پرسنل')
    contractor_delivery = models.ForeignKey(Contractors, on_delete=models.CASCADE, related_name='project_warehouse_contractors_deliveries',null=True, blank=True,verbose_name='پیمانکار')
    status = models.CharField(max_length=3, choices=STATUS_CHOICES, verbose_name='وضعیت')
    export_import_date = jmodels.jDateField(verbose_name='تاریخ ورود/خروج')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)
    
    objects = ProjectWarehouseManager()


    class Meta:
        verbose_name = "کالای انبار پروژه"
        verbose_name_plural = "کالاهای انبار پروژه"

    def __str__(self):
        if self.status == 'exp':
            return f"{self.stuff_type} - خروج از انبار "
        else:
            return f"{self.stuff_type} - ورود به انبار "
    
    def formatted_stuff_amount(self):

templates/warehousing/tables/project_warehouses_table.html
{% load jformat %}

<div class="row">
    <div class="col-sm-12 table-responsive">
        <p class="mb-3">برای مشاهده موجودی کالاهای هر پروژه بر روی نام پروژه کلیک کنید</p>
        <table id="data-table" class="table table-bordered table-striped sortable" role="grid" aria-describedby="example1_info">
            <thead>
                <tr role="row">
                    <th class="text-center border-bottom-0 rounded-0" rowspan="2" colspan="1" style="width: 40.797px;">
                        ردیف
                    </th>

                    <th class="text-center" rowspan="2" colspan="1" style="width: 100.797px;">
                        <span>&emsp;&emsp;</span>
                        <span>پروژه</span>
                        <span>&emsp;&emsp;</span>
                    </th>

                    <td class="text-center text-light" rowspan="1" colspan="2" style="width: 100.797px;background-color: #808080;">
                        کالا
                    </td>

                    <td class="text-center text-light" rowspan="1" colspan="2" style="width: 100.797px;background-color: #808080;">
                        درخواست کننده
                    </td>

                    <td class="text-center text-light" rowspan="1" colspan="2" style="width: 100.797px;background-color: #808080;">
                        تحویل گیرنده
                    </td>

                    <th class="text-center" rowspan="2" colspan="1" style="width: 100.797px;">
                        <span>&emsp;</span>
                        <span>وضعیت</span>
                        <span>&emsp;</span>
                    </th>

                    <th class="text-center" rowspan="2" colspan="1" style="width: 100.797px;">
                        تاریخ ورود/خروج
                    </th>

                    <th class="text-center border-left" rowspan="2" colspan="1" style="width: 236.094px;">
                        <span>&emsp;</span>
                        <span>زمان ثبت</span>
                        <span>&emsp;</span>
                    </th>

                    <th class="text-center border-left" rowspan="2" colspan="1" style="width: 236.094px;">
                        زمان آخرین ویرایش
                    </th>
                    
                    {% if perms.warehousing.delete_projectwarehouse or perms.warehousing.change_projectwarehouse %}
                        <th class=" text-center border-bottom-0 action-th rounded-0" rowspan="2" colspan="1" style="width: 100.797px;">
                            <span>&emsp;&emsp;&emsp;</span>
                            <span>اقدام</span>
                            <span>&emsp;&emsp;&emsp;</span>
                        </th>
                    {% endif %}
                </tr>
                <tr role="row">
                    <th class="text-center" rowspan="1" colspan="1" style="width: 100.797px;">
                        نوع کالا
                    </th>

                    <th class="text-center" rowspan="1" colspan="1" style="width: 100.797px;">
                        <span>&emsp;&emsp;</span>
                        <span>مقدار</span>
                        <span>&emsp;&emsp;</span>
                    </th>

                    <th class="text-center" rowspan="1" colspan="1" style="width: 100.797px;">
                        <span>&emsp;&emsp;</span>
                        <span>پرسنل</span>
                        <span>&emsp;&emsp;</span>
                    </th>

                    <th class="text-center" rowspan="1" colspan="1" style="width: 100.797px;">
                        <span>&emsp;&emsp;</span>
                        <span>پیمانکار</span>
                        <span>&emsp;&emsp;</span>
                    </th>

                    <th class="text-center" rowspan="1" colspan="1" style="width: 100.797px;">
                        <span>&emsp;&emsp;</span>
                        <span>پرسنل</span>
                        <span>&emsp;&emsp;</span>
                    </th>

                    <th class="text-center" rowspan="1" colspan="1" style="width: 100.797px;">
                        <span>&emsp;&emsp;</span>
                        <span>پیمانکار</span>
                        <span>&emsp;&emsp;</span>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for project_warehouse in project_warehouses %}
                    {% for row, object in records_dict.items %}
                        {% if project_warehouse.pk == object.pk %}
                            <tr role="row" class="odd">
                                <td>{{ row }}</td>
                                <td>
                                    <a href="{% url 'reports:project_stuffs' project_warehouse.project.title %}"
                                    class="nav-link">
                                        {{ project_warehouse.project }}
                                    </a>
                                </td>
                                <td>{{ project_warehouse.stuff_type.stuff_type }}</td>

                                <td data-sort="{{ project_warehouse.stuff_amount }}">
                                    {{ project_warehouse.formatted_stuff_amount }}
                                    {{ project_warehouse.stuff_type.persian_measurement_unit }}
                                </td>
                                
                                {% if project_warehouse.personnel_apply %}
                                    <td>{{ project_warehouse.personnel_apply }}</td>
                                {% else %}
                                    <td class="text-center">_</td>
                                {% endif %}

                                {% if project_warehouse.contractor_apply %}
                                    <td>{{ project_warehouse.contractor_apply }}</td>
                                {% else %}
                                    <td class="text-center">_</td>
                                {% endif %}

                                {% if project_warehouse.personnel_delivery %}
                                    <td>{{ project_warehouse.personnel_delivery }}</td>
                                {% else %}
                                    <td class="text-center">_</td>
                                {% endif %}

                                {% if project_warehouse.contractor_delivery %}
                                    <td>{{ project_warehouse.contractor_delivery }}</td>
                                {% else %}
                                    <td class="text-center">_</td>
                                {% endif %}

                                <td>
                                    {% if project_warehouse.status == 'exp' %}
                                        خروج از انبار   
                                    {% else %}
                                        ورود به انبار   
                                    {% endif %}
                                </td>
                                <td data-sort="{{ project_warehouse.import_date|date:'Ymd' }}">
                                    {{ project_warehouse.export_import_date|jformat:'%d / %m / %Y' }}
                                </td>

                                <td data-sort="{{ project_warehouse.create_record|date:'Ymd-HMS' }}" class="border-left">
                                    {{ project_warehouse.create_record|jformat:'%Y/%m/%d - %H:%M:%S' }}
                                </td>
                                {% if project_warehouse.update_record|date:'Ymd-HMS' == project_warehouse.create_record|date:'Ymd-HMS' %}
                                    <td class="text-center">
                                        <span style="font-size:1.5rem;">_</span>
                                    </td>
                                {% else %}
                                    <td data-sort="{{ project_warehouse.update_record|date:'Ymd-HMS' }}" class="border-left">
                                        {{ project_warehouse.update_record|jformat:'%Y/%m/%d - %H:%M:%S' }}
                                    </td>
                                {% endif %}
                                
                                {% if perms.warehousing.delete_projectwarehouse or perms.warehousing.change_projectwarehouse %}
                                    <td class="action-td d-flex justify-content-center rounded-0 pb-4">
                                        {% if perms.warehousing.change_projectwarehouse %}
                                            <a href="{% url 'warehousing:project_warehouse_update' project_warehouse.pk %}" 
                                            class="btn btn-outline-info mb-2 pb-0" title="ویرایش">
                                            <i class="fa-solid fa-pen-to-square"></i>
                                            </a>
                                        {% endif %}

                                        {% if perms.warehousing.delete_projectwarehouse %}
                                            <a href="javascript:void(0)"  
                                            data-toggle="modal"
                                            class="btn btn-outline-danger mb-2 ml-2 pb-0"
                                            data-url="{% url 'warehousing:project_warehouse_delete' pk=project_warehouse.pk %}"
                                            data-target="#deleteItemModal" title="حذف"
                                            data-message="آیا از حذف این عملیات اطمینان دارید؟">
                                            <i class="fa-solid fa-xmark" style="font-size: 1.2rem;"></i>
                                            </a>
                                        {% endif %}

                                        {% if perms.warehousing.view_projectwarehouse %}
                                            <a href="{% url 'reports:project_warehouse_report' project_warehouse.pk %}" 
                                            class="btn btn-outline-info mb-2 pb-0" title="مشاهده گزارش">
                                            <i class="fa-solid fa-paste"></i>
                                            </a>
                                        {% endif %}
                                    </td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/warehousing/tables/stuffs_table.html
{% load warehousing_tags %}

<div class="row">
    <div class="col-sm-6 offset-sm-3 table-responsive">
        <table id="data-table" class="table table-bordered table-striped dataTable sortable" role="grid" aria-describedby="example1_info">
            <thead>
                <tr role="row">

                    <th class="text-center rounded-0" rowspan="1" colspan="1" style="width: 358.797px;;">
                        ردیف
                    </th>

                    <th class="text-center rounded-0" rowspan="1" colspan="1" style="width: 358.797px;;">
                        نوع کالا
                    </th>

                    <th class="text-center rounded-0" rowspan="1" colspan="1" style="width: 358.797px;;">
                        موجودی انبار اصلی
                    </th>

                    {% if perms.warehousing.delete_stuff or perms.warehousing.change_stuff %}
                        <th class="text-center border-left rounded-0 action-th" rowspan="1" colspan="1" style="width: 236.094px;">
                            <span>&emsp;&emsp;</span>
                            <span>اقدام</span>
                            <span>&emsp;&emsp;</span>
                        </th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for stuff in stuffs %}
                    {% for row, object in records_dict.items %}
                        {% if stuff.pk == object.pk %}
                            <tr role="row" class="odd">
                                <td class="border-bottom">{{ row }}</td>
                                <td class="border-bottom">{{ stuff.stuff_type }}</td>

                                {% total_stock stuff.stuff_type stuff.measurement_unit %}

                                {% if perms.warehousing.delete_stuff or perms.warehousing.change_stuff %}
                                    <td class="border-left text-center action-td border-bottom">
                                        {% if perms.warehousing.change_stuff %}
                                            <a href="{% url 'warehousing:stuff_update' stuff.pk %}" 
                                            class="btn btn-outline-info mb-2 pb-0" title="ویرایش">
                                            <i class="fa-solid fa-pen-to-square"></i>
                                            </a>
                                        {% endif %}
                                        
                                        {% if perms.warehousing.delete_stuff %}
                                            <a href="javascript:void(0)"  
                                                data-toggle="modal"
                                                class="btn btn-outline-danger mb-2 ml-2 pb-0"
                                                data-url="{% url 'warehousing:stuff_delete' pk=stuff.pk %}"
                                                data-target="#deleteItemModal" title="حذف"
                                                data-message="آیا از حذف '{{ stuff.stuff_type }}' اطمینان دارید؟">
                                                <i class="fa-solid fa-xmark" style="font-size: 1.2rem;"></i>
                                            </a>
                                        {% endif %}
                                    </td>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>