account/urls.py
from django.urls import path

from .views import (
    UsersList, CreateUser, UpdateUser, DeleteUser, SearchUsers,
    GroupList, CreateGroup, UpdateGroup, DeleteGroup, SearchGroups,
    EditAccount, ChangeUserPassword
)

app_name = "account"

urlpatterns = [
    path('users/', UsersList.as_view(), name="users"),
    path('users/page/<int:page>', UsersList.as_view(), name="users"),
    path('users/search', SearchUsers.as_view(), name="users_search"),
    path('users/search/page/<int:page>', SearchUsers.as_view(), name="users_search"),
    path('users/create', CreateUser.as_view(), name="user_create"),
    path('users/update/<int:pk>', UpdateUser.as_view(), name="user_update"),
    path('users/change_password/<int:pk>', ChangeUserPassword.as_view(), name="change_user_password"),
    path('users/delete/<int:pk>', DeleteUser.as_view(), name="user_delete"),

    path('groups/', GroupList.as_view(), name="groups"),
    path('groups/page/<int:page>', GroupList.as_view(), name="groups"),
    path('groups/search', SearchGroups.as_view(), name="groups_search"),
    path('groups/search/page/<int:page>', SearchGroups.as_view(), name="groups_search"),
    path('groups/create', CreateGroup.as_view(), name="group_create"),
    path('groups/update/<int:pk>', UpdateGroup.as_view(), name="group_update"),
    path('groups/delete/<int:pk>', DeleteGroup.as_view(), name="group_delete"),

    path('edit_account/<str:username>', EditAccount.as_view(), name="edit_account")
] 

configs/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from .views import index
from account.views import Login, log_out, ChangePassword

urlpatterns = [
    path('', index, name="index"),
    path('government_accounts/', include('government_accounts.urls')),
    path('non_government_accounts/', include('non_government_accounts.urls')),
    path('projects/', include('projects.urls')),
    path('cheques_receive_pay/', include('cheques_receive_pay.urls')),
    path('warehousing/', include('warehousing.urls')),
    path('projects_docs/', include('projects_docs.urls')),
    path('login/', Login.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('change_password/', ChangePassword.as_view(), name='change_password'),
    path('account/', include('account.urls')),
    path('reports/', include('reports.urls')),
    path('user_messages/', include('user_messages.urls')),
    path('admin/', admin.site.urls, name="home"),
]

handler404 = 'configs.views.custom_404'
handler500 = 'configs.views.custom_500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

warehousing/urls.py
from django.urls import path

from .views import (
    StuffList, StuffCreate, StuffUpdate, StuffDelete, StuffSearch,
    WarehouseImportList, WarehouseImportCreate, WarehouseImportUpdate, WarehouseImportDelete, WarehouseImportSearch,
    WarehouseExportList, WarehouseExportCreate, WarehouseExportUpdate, WarehouseExportDelete, WarehouseExportSearch,
    UseCertificateList, UseCertificateCreate, UseCertificateUpdate, UseCertificateDelete, UseCertificateSearch,
    ProjectWarehouseList, ProjectWarehouseCreate, ProjectWarehouseUpdate, ProjectWarehouseDelete, ProjectWarehouseSearch
)



app_name = 'warehousing'

urlpatterns = [
    path('stuffs/', StuffList.as_view(), name='stuffs'),
    path('stuffs/page/<int:page>', StuffList.as_view(), name='stuffs'),
    path('stuffs/search', StuffSearch.as_view(), name='stuffs_search'),
    path('stuffs/search/page/<int:page>', StuffSearch.as_view(), name='stuffs_search'),
    path('stuffs/create', StuffCreate.as_view(), name='stuff_create'),
    path('stuffs/update/<int:pk>', StuffUpdate.as_view(), name='stuff_update'),
    path('stuffs/delete/<int:pk>', StuffDelete.as_view(), name='stuff_delete'),

    path('warehouse_imports/', WarehouseImportList.as_view(), name='warehouse_imports'),
    path('warehouse_imports/page/<int:page>', WarehouseImportList.as_view(), name='warehouse_imports'),
    path('warehouse_imports/search', WarehouseImportSearch.as_view(), name='warehouse_imports_search'),
    path('warehouse_imports/search/page/<int:page>', WarehouseImportSearch.as_view(), name='warehouse_imports_search'),
    path('warehouse_imports/create', WarehouseImportCreate.as_view(), name='warehouse_import_create'),
    path('warehouse_imports/update/<int:pk>', WarehouseImportUpdate.as_view(), name='warehouse_import_update'),
    path('warehouse_imports/delete/<int:pk>', WarehouseImportDelete.as_view(), name='warehouse_import_delete'),

    path('warehouse_exports/', WarehouseExportList.as_view(), name='warehouse_exports'),
    path('warehouse_exports/page/<int:page>', WarehouseExportList.as_view(), name='warehouse_exports'),
    path('warehouse_exports/search', WarehouseExportSearch.as_view(), name='warehouse_exports_search'),
    path('warehouse_exports/search/page/<int:page>', WarehouseExportSearch.as_view(), name='warehouse_exports_search'),
    path('warehouse_exports/create', WarehouseExportCreate.as_view(), name='warehouse_export_create'),
    path('warehouse_exports/update/<int:pk>', WarehouseExportUpdate.as_view(), name='warehouse_export_update'),
    path('warehouse_exports/delete/<int:pk>', WarehouseExportDelete.as_view(), name='warehouse_export_delete'),

    path('use_certificates/', UseCertificateList.as_view(), name='use_certificates'),
    path('use_certificates/page/<int:page>', UseCertificateList.as_view(), name='use_certificates'),
    path('use_certificates/search', UseCertificateSearch.as_view(), name='use_certificates_search'),
    path('use_certificates/search/page/<int:page>', UseCertificateSearch.as_view(), name='use_certificates_search'),
    path('use_certificates/create', UseCertificateCreate.as_view(), name='use_certificate_create'),
    path('use_certificates/update/<int:pk>', UseCertificateUpdate.as_view(), name='use_certificate_update'),
    path('use_certificates/delete/<int:pk>', UseCertificateDelete.as_view(), name='use_certificate_delete'),

    path('project_warehouses/', ProjectWarehouseList.as_view(), name='project_warehouses'),
    path('project_warehouses/page/<int:page>', ProjectWarehouseList.as_view(), name='project_warehouses'),
    path('project_warehouses/search', ProjectWarehouseSearch.as_view(), name='project_warehouses_search'),
    path('project_warehouses/search/page/<int:page>', ProjectWarehouseSearch.as_view(), name='project_warehouses_search'),
    path('project_warehouses/create', ProjectWarehouseCreate.as_view(), name='project_warehouse_create'),
    path('project_warehouses/update/<int:pk>', ProjectWarehouseUpdate.as_view(), name='project_warehouse_update'),
    path('project_warehouses/delete/<int:pk>', ProjectWarehouseDelete.as_view(), name='project_warehouse_delete'),
]

warehousing/models.py
from django.db import models
from django.db.models.query import Q

from django_jalali.db import models as jmodels

from projects.models import Project
from non_government_accounts.models import Suppliers, Personnel, Contractors




class StuffManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(stuff_type__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class Stuff(models.Model):
    MEASUREMENT_UNIT_CHOICES = (
        ('sqm', 'مترمربع'),
        ('mel', 'مترطول'),
        ('kgm', 'کیلوگرم'),
        ('ton', 'تن'),
        ('num', 'عدد'),
        ('bag', 'کیسه'),
    )
    stuff_type = models.CharField(max_length=100, verbose_name='نوع کالا')
    measurement_unit = models.CharField(max_length=3, choices=MEASUREMENT_UNIT_CHOICES, verbose_name='واحد اندازه گیری')
    
    objects = StuffManager()
    

    class Meta:
        verbose_name = "کالا"
        verbose_name_plural = "کالاها"

    def __str__(self):
        return f'{self.stuff_type} - واحد: {self.persian_measurement_unit()}'
    
    def persian_measurement_unit(self):
        if self.measurement_unit == "sqm":
            return 'مترمربع' 
        elif self.measurement_unit == "mel":
            return 'متر طول' 
        elif self.measurement_unit == "kgm":
            return 'کیلوگرم' 
        elif self.measurement_unit == "ton":
            return 'تن' 
        elif self.measurement_unit == "num":
            return 'عدد' 
        else:
            return 'کیسه'


class MainWarehouseImportManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(supplier__full_name__icontains=query)|
            Q(receiver__full_name__icontains=query)|
            Q(other_sender__icontains=query)|
            Q(stuff_type__stuff_type__icontains=query)|
            Q(project_returned__title__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class MainWarehouseImport(models.Model):
    # sender
    supplier = models.ForeignKey(Suppliers, on_delete=models.CASCADE, related_name='warehouse_import_suppliers', null=True, blank=True,verbose_name='تأمین کننده')
    other_sender = models.TextField(null=True, blank=True, verbose_name='سایر')
    # stuff
    stuff_type = models.ForeignKey(Stuff,on_delete=models.CASCADE,related_name='warehouse_import_stuffs',verbose_name='نوع کالا')
    stuff_amount = models.PositiveIntegerField(default=0, verbose_name='مقدار')
    receiver = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='warehouse_import_personnel', verbose_name='تحویل گیرنده')
    import_date = jmodels.jDateField(verbose_name='تاریخ ورود کالا')
    # returned
    is_returned = models.BooleanField(default=False, verbose_name='کالا مرجوعی است')
    project_returned = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='warehouse_returned_projects', null=True, blank=True,verbose_name='مرجوعی از پروژه')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = MainWarehouseImportManager()


    class Meta:
        verbose_name = "کالای افزوده شده به انبار"
        verbose_name_plural = "کالاهای افزوده شده به انبار"

    def __str__(self):
        return f"{self.stuff_type} - {self.date_time.year}/{self.date_time.month}/{self.date_time.day}" # type: ignore
    
    def formatted_stuff_amount(self):
        return "{:,}".format(self.stuff_amount)
    
    
class MainWarehouseExportManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(personnel__full_name__icontains=query)|
            Q(contractor__full_name__icontains=query)|
            Q(deliverer__full_name__icontains=query)|
            Q(stuff_type__stuff_type__icontains=query)|
            Q(project__title__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class MainWarehouseExport(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='warehouse_export_projects', verbose_name='پروژه')
    # applicant
    personnel = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='warehouse_export_personnel', null=True, blank=True, verbose_name='پرسنل')
    contractor = models.ForeignKey(Contractors, on_delete=models.CASCADE, related_name='warehouse_export_contractors', null=True, blank=True, verbose_name='پیمانکار')
    # stuff
    stuff_type = models.ForeignKey(Stuff, on_delete=models.CASCADE, related_name='warehouse_export_stuffs', verbose_name='نوع کالا')
    stuff_amount = models.PositiveIntegerField(default=0, verbose_name='مقدار')
    deliverer = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='warehouse_export_deliverers', verbose_name='تحویل دهنده')
    export_date = jmodels.jDateField(verbose_name='تاریخ خروج کالا')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)

    objects = MainWarehouseExportManager()

    class Meta:
        verbose_name = "کالای خارج شده از انبار"
        verbose_name_plural = "کالاهای خارج شده از انبار"

    def __str__(self):
        return f"{self.stuff_type} - {self.project}"
    
    def formatted_stuff_amount(self):
        return "{:,}".format(self.stuff_amount)
    

class UseCertificateManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(project__title__icontains=query)|
            Q(stuff_type__stuff_type__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class UseCertificate(models.Model):
    RETURNED_TO_CHOICES = (
        ('prw', 'انبار پروژه'),
        ('maw', 'انبار اصلی'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='use_certificate_projects',verbose_name='پروژه')
    # stuff
    stuff_type = models.ForeignKey(Stuff, on_delete=models.CASCADE, related_name='use_certificate_stuffs', verbose_name='نوع کالا')
    is_deficient = models.BooleanField(default=False, verbose_name='کسری دارد')
    deficient_amount = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name='مقدار کسری')
    is_excess = models.BooleanField(default=False, verbose_name='مازاد دارد')
    excess_amount = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name='مقدار مازاد')
    start_using_date = jmodels.jDateField(verbose_name='تاریخ شروع مصرف')
    finish_using_date = jmodels.jDateField(verbose_name='تاریخ پایان مصرف')
    # returned
    returned_to = models.CharField(max_length=3, choices=RETURNED_TO_CHOICES, null=True, blank=True, verbose_name='مرجوعی به')
    return_date = jmodels.jDateField(null=True, blank=True, verbose_name='تاریخ ارجاع به انبار')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)
    
    objects = UseCertificateManager()

    class Meta:
        verbose_name = "گواهی مصرف کالا"
        verbose_name_plural = "گواهی‌های مصرف کالا"

    def __str__(self):
        return f"{self.project.title}-{self.stuff_type.stuff_type}: از {self.start_using_date.year}/{self.start_using_date.month}/{self.start_using_date.day} - تا {self.finish_using_date.year}/{self.finish_using_date.month}/{self.finish_using_date.day}"
    
    def formatted_deficient_amount(self):
        return "{:,}".format(self.deficient_amount)
    
    def formatted_excess_amount(self):
        return "{:,}".format(self.excess_amount)


class ProjectWarehouseManager(models.Manager):
    def search(self, query):
        lookup = (
            Q(project__title__icontains=query)|
            Q(personnel_apply__full_name__icontains=query)|
            Q(contractor_apply__full_name__icontains=query)|
            Q(personnel_delivery__full_name__icontains=query)|
            Q(contractor_delivery__full_name__icontains=query)|
            Q(stuff_type__stuff_type__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class ProjectWarehouse(models.Model):
    STATUS_CHOICES = (
        ('exp', 'خروج از انبار'),
        ('imp', 'ورود به انبار'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_warehouse_projects',verbose_name='پروژه')
    # applicant
    personnel_apply = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='project_warehouse_personnel_applies',null=True, blank=True,verbose_name='پرسنل')
    contractor_apply = models.ForeignKey(Contractors, on_delete=models.CASCADE, related_name='project_warehouse_contractors_applies',null=True, blank=True,verbose_name='پیمانکار')
     # stuff
    stuff_type = models.ForeignKey(Stuff, on_delete=models.CASCADE, related_name='project_warehouse_stuffs', verbose_name='نوع کالا')
    stuff_amount = models.PositiveIntegerField(default=0, verbose_name='مقدار')
    # deliverer
    personnel_delivery = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name='project_warehouse_personnel_deliveries',null=True, blank=True,verbose_name='پرسنل')
    contractor_delivery = models.ForeignKey(Contractors, on_delete=models.CASCADE, related_name='project_warehouse_contractors_deliveries',null=True, blank=True,verbose_name='پیمانکار')
    status = models.CharField(max_length=3, choices=STATUS_CHOICES, verbose_name='وضعیت')
    export_import_date = jmodels.jDateField(verbose_name='تاریخ ورود/خروج')
    create_record = jmodels.jDateTimeField(auto_now_add=True)
    update_record = jmodels.jDateTimeField(auto_now=True)
    
    objects = ProjectWarehouseManager()


    class Meta:
        verbose_name = "کالای انبار پروژه"
        verbose_name_plural = "کالاهای انبار پروژه"

    def __str__(self):
        if self.status == 'exp':
            return f"{self.stuff_type} - خروج از انبار "
        else:
            return f"{self.stuff_type} - ورود به انبار "
    
    def formatted_stuff_amount(self):

templates/warehousing/project_warehouse_create_update.html
{% extends 'base_create_update.html' %}
{% load static %}

{% block title %}
    {% if request.resolver_match.url_name == 'project_warehouse_create' %}
        ثبت ورود و خروج کالا به انبار پروژه 
    {% else %}
        ویرایش ورود و خروج کالا به انبار پروژه
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'project_warehouse_create' %}
        <span>ثبت ورود و خروج کالا به انبار پروژه</span>
    {% else %}
        <span>ویرایش ورود و خروج کالا به انبار پروژه</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "warehousing/forms/project_warehouse_form.html" %}
{% endblock %}

{% block form_control %}
    <script src="{% static 'scripts/warehousing/project_warehouses_form.js' %}"></script>
{% endblock %}

templates/warehousing/project_warehouses_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست ورود و خروج کالا به انبار پروژه{% endblock %}

{% block page_title %}لیست ورود و خروج کالا به انبار پروژه{% endblock %}

{% block filter %}
    {% include 'warehousing/filters/project_warehouses_filter.html' with search_url=search_url date_filter=True create_url=create_url list_url=list_url title='ثبت عملیات انبار پروژه' create_perm=perms.warehousing.add_projectwarehouse %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include 'warehousing/tables/project_warehouses_table.html' %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/warehousing/project_warehouses_list.js' %}"></script>
{% endblock %}

templates/warehousing/stuff_create_update.html
{% extends 'base_create_update.html' %}

{% block title %}
    {% if request.resolver_match.url_name == 'stuff_create' %}
        افزودن کالا
    {% else %}
        ویرایش کالا
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'stuff_create' %}
        <span>افزودن کالا</span>
    {% else %}
        <span>ویرایش کالا</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "warehousing/forms/stuff_form.html" %}
{% endblock %}

templates/warehousing/stuffs_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست کالاها{% endblock %}

{% block page_title %}لیست کالاها{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=False create_url=create_url list_url=list_url title='افزودن کالا' create_perm=perms.warehousing.add_stuff %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count None None list_filters False %}
    {% else %}
        {% objects_records list_url None record_number records_count None None None False %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include 'warehousing/tables/stuffs_table.html' %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}

{% block filter_control %}
    <script src="{% static 'scripts/warehousing/stuffs_list.js' %}"></script>
{% endblock %}

templates/warehousing/use_certificate_create_update.html
{% extends 'base_create_update.html' %}
{% load static %}

{% block title %}
    {% if request.resolver_match.url_name == 'use_certificate_create' %}
        ثبت گواهی مصرف 
    {% else %}
        ویرایش گواهی مصرف
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'use_certificate_create' %}
        <span>ثبت گواهی مصرف</span>
    {% else %}
        <span>ویرایش گواهی مصرف</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "warehousing/forms/use_certificate_form.html" %}
{% endblock %}

{% block form_control %}
    <script src="{% static 'scripts/warehousing/use_certificate_form.js' %}"></script>
{% endblock %}

templates/warehousing/use_certificates_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست گواهی‌های مصرف کالا{% endblock %}

{% block page_title %}لیست گواهی‌های مصرف کالا{% endblock %}

{% block filter %}
    {% include 'warehousing/filters/use_certificates_filter.html' with search_url=search_url date_filter=False create_url=create_url list_url=list_url title='ثبت عملیات تنخواه' create_perm=perms.warehousing.add_usecertificate %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include 'warehousing/tables/use_certificates_table.html' %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}
 
{% block filter_control %}
    <script src="{% static 'scripts/warehousing/use_certificates_list.js' %}"></script>
{% endblock %}

templates/warehousing/warehouse_export_create_update.html
{% extends 'base_create_update.html' %}
{% load static %}

{% block title %}
    {% if request.resolver_match.url_name == 'warehouse_export_create' %}
        ثبت خروج کالا از انبار 
    {% else %}
        ویرایش کالای خارج شده از انبار
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'warehouse_export_create' %}
        <span>ثبت خروج کالا از انبار</span>
    {% else %}
        <span>ویرایش کالای خارج شده از انبار</span>
    {% endif %}
{% endblock %}

{% block extra_cart %}
    {% include "warehousing/tables/stuffs_type_table.html" with stuffs=stuffs %}
{% endblock %}

{% block form %}
	{% include "warehousing/forms/warehouse_export_form.html" %}
{% endblock %}

{% block form_control %}
    <script src="{% static 'scripts/warehousing/warehouse_export_form.js' %}"></script>
{% endblock %}

templates/warehousing/warehouse_exports_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست کالاهای خارج شده از انبار اصلی{% endblock %}

{% block page_title %}لیست کالاهای خارج شده از انبار اصلی{% endblock %}

{% block filter %}
    {% include 'partials/search_print.html' with search_url=search_url date_filter=True create_url=create_url list_url=list_url title='افزودن کالا به انبار' create_perm=perms.warehousing.add_mainwarehouseexport %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include 'warehousing/tables/warehouse_exports_table.html' %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}
    
{% block filter_control %}
    <script src="{% static 'scripts/warehousing/warehouse_exports_list.js' %}"></script>
{% endblock %}

templates/warehousing/warehouse_import_create_update.html
{% extends 'base_create_update.html' %}
{% load static %}

{% block title %}
    {% if request.resolver_match.url_name == 'warehouse_import_create' %}
        ثبت ورود کالا به انبار 
    {% else %}
        ویرایش کالای وارد شده به انبار
    {% endif %} 
{% endblock %}

{% block page_title %}
    {% if request.resolver_match.url_name == 'warehouse_import_create' %}
        <span>ثبت ورود کالا به انبار</span>
    {% else %}
        <span>ویرایش کالای وارد شده به انبار</span>
    {% endif %}
{% endblock %}

{% block form %}
	{% include "warehousing/forms/warehouse_import_form.html" %}
{% endblock %}

{% block form_control %}
    <script src="{% static 'scripts/warehousing/warehouse_import_form.js' %}"></script>
{% endblock %}

templates/warehousing/warehouse_imports_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load base_tags %}

{% block title %}لیست کالاهای وارد شده به انبار اصلی{% endblock %}

{% block page_title %}لیست کالاهای وارد شده به انبار اصلی{% endblock %}

{% block filter %}
    {% include 'warehousing/filters/warehouse_imports_filter.html' with search_url=search_url date_filter=True create_url=create_url list_url=list_url title='افزودن کالا به انبار' create_perm=perms.warehousing.add_mainwarehouseimport %}
{% endblock %}

{% block record_control %}
    {% if 'search' in request.resolver_match.url_name %}
        {% objects_records None search_url record_number records_count fields_order order_by list_filters %}
    {% else %}
        {% objects_records list_url None record_number records_count fields_order order_by %}
    {% endif %}
{% endblock %}

{% block table %}
    {% include 'warehousing/tables/warehouse_imports_table.html' %}
{% endblock %}

{% block pagination %}
    {% include 'partials/objects_pagination.html' %}
{% endblock %}
    
{% block filter_control %}
    <script src="{% static 'scripts/warehousing/warehouse_imports_list.js' %}"></script>
{% endblock %}